/*
 * This file is part of node-toxcore.
 *
 * node-toxcore is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * node-toxcore is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with node-toxcore. If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * @file consts.js
 * Specifies constants and enum values defined in tox.h. All enum values
 * are assumed to start at 0 and increment once per possible value. This
 * could be an issue if updated versions of toxcore have new enum values
 * inserted, instead of appended.
 */

var consts = {
  TOX_KEY_SIZE: 32,
  TOX_FRIEND_ADDRESS_SIZE: (32 + 6),

  TOX_PUBLIC_KEY_SIZE: 32,
  TOX_SECRET_KEY_SIZE: 32,
  TOX_ADDRESS_SIZE: (32 + 6),
  TOX_MAX_NAME_LENGTH: 128,
  TOX_MAX_STATUS_MESSAGE_LENGTH: 1007,
  TOX_MAX_FRIEND_REQUEST_LENGTH: 1016,
  TOX_MAX_MESSAGE_LENGTH: 1372,
  TOX_MAX_CUSTOM_PACKET_SIZE: 1373,
  TOX_HASH_LENGTH: 32,
  TOX_FILE_ID_LENGTH: 32,
  TOX_MAX_FILENAME_LENGTH: 255,

  TOX_CONNECTION_NONE: 0,
  TOX_CONNECTION_TCP: 1,
  TOX_CONNECTION_UDP: 2,

  TOX_MESSAGE_TYPE_NORMAL: 0,
  TOX_MESSAGE_TYPE_ACTION: 1,

  TOX_USER_STATUS_NONE: 0,
  TOX_USER_STATUS_AWAY: 1,
  TOX_USER_STATUS_BUSY: 2,

  TOX_ERR_FILE_CONTROL_OK: 0,
  TOX_ERR_FILE_CONTROL_FRIEND_NOT_FOUND: 1,
  TOX_ERR_FILE_CONTROL_FRIEND_NOT_CONNECTED: 2,
  TOX_ERR_FILE_CONTROL_NOT_FOUND: 3,
  TOX_ERR_FILE_CONTROL_NOT_PAUSED: 4,
  TOX_ERR_FILE_CONTROL_DENIED: 5,
  TOX_ERR_FILE_CONTROL_ALREADY_PAUSED: 6,
  TOX_ERR_FILE_CONTROL_SENDQ: 7,

  TOX_ERR_FILE_GET_OK: 0,
  TOX_ERR_FILE_GET_FRIEND_NOT_FOUND: 1,
  TOX_ERR_FILE_GET_NOT_FOUND: 2,

  TOX_ERR_FILE_SEEK_OK: 0,
  TOX_ERR_FILE_SEEK_FRIEND_NOT_FOUND: 1,
  TOX_ERR_FILE_SEEK_FRIEND_NOT_CONNECTED: 2,
  TOX_ERR_FILE_SEEK_NOT_FOUND: 3,
  TOX_ERR_FILE_SEEK_DENIED: 4,
  TOX_ERR_FILE_SEEK_INVALID_POSITION: 5,
  TOX_ERR_FILE_SEEK_SENDQ: 6,

  TOX_ERR_FILE_SEND_OK: 0,
  TOX_ERR_FILE_SEND_NULL: 1,
  TOX_ERR_FILE_SEND_FRIEND_NOT_FOUND: 2,
  TOX_ERR_FILE_SEND_FRIEND_NOT_CONNECTED: 3,
  TOX_ERR_FILE_SEND_NAME_TOO_LONG: 4,
  TOX_ERR_FILE_SEND_TOO_MANY: 5,

  TOX_ERR_FILE_SEND_CHUNK_OK: 0,
  TOX_ERR_FILE_SEND_CHUNK_NULL: 1,
  TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_FOUND: 2,
  TOX_ERR_FILE_SEND_CHUNK_FRIEND_NOT_CONNECTED: 3,
  TOX_ERR_FILE_SEND_CHUNK_NOT_FOUND: 4,
  TOX_ERR_FILE_SEND_CHUNK_NOT_TRANSFERRING: 5,
  TOX_ERR_FILE_SEND_CHUNK_INVALID_LENGTH: 6,
  TOX_ERR_FILE_SEND_CHUNK_SENDQ: 7,
  TOX_ERR_FILE_SEND_CHUNK_WRONG_POSITION: 8,

  TOX_ERR_FRIEND_ADD_OK: 0,
  TOX_ERR_FRIEND_ADD_NULL: 1,
  TOX_ERR_FRIEND_ADD_TOO_LONG: 2,
  TOX_ERR_FRIEND_ADD_NO_MESSAGE: 3,
  TOX_ERR_FRIEND_ADD_OWN_KEY: 4,
  TOX_ERR_FRIEND_ADD_ALREADY_SENT: 5,
  TOX_ERR_FRIEND_ADD_BAD_CHECKSUM: 6,
  TOX_ERR_FRIEND_ADD_SET_NEW_NOSPAM: 7,
  TOX_ERR_FRIEND_ADD_MALLOC: 8,

  TOX_ERR_FRIEND_CUSTOM_PACKET_OK: 0,
  TOX_ERR_FRIEND_CUSTOM_PACKET_NULL: 1,
  TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_FOUND: 2,
  TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_CONNECTED: 3,
  TOX_ERR_FRIEND_CUSTOM_PACKET_INVALID: 4,
  TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY: 5,
  TOX_ERR_FRIEND_CUSTOM_PACKET_TOO_LONG: 6,
  TOX_ERR_FRIEND_CUSTOM_PACKET_SENDQ: 7,

  TOX_ERR_FRIEND_DELETE_OK: 0,
  TOX_ERR_FRIEND_DELETE_FRIEND_NOT_FOUND: 1,

  TOX_ERR_FRIEND_GET_LAST_ONLINE_OK: 0,
  TOX_ERR_FRIEND_GET_LAST_ONLINE_FRIEND_NOT_FOUND: 1,

  TOX_ERR_FRIEND_QUERY_OK: 0,
  TOX_ERR_FRIEND_QUERY_NULL: 1,
  TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND: 2,

  TOX_ERR_FRIEND_SEND_MESSAGE_OK: 0,
  TOX_ERR_FRIEND_SEND_MESSAGE_NULL: 1,
  TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_FOUND: 2,
  TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_CONNECTED: 3,
  TOX_ERR_FRIEND_SEND_MESSAGE_SENDQ: 4,
  TOX_ERR_FRIEND_SEND_MESSAGE_TOO_LONG: 5,
  TOX_ERR_FRIEND_SEND_MESSAGE_EMPTY: 6,

  TOX_ERR_NEW_OK: 0,
  TOX_ERR_NEW_NULL: 1,
  TOX_ERR_NEW_MALLOC: 2,
  TOX_ERR_NEW_PORT_ALLOC: 3,
  TOX_ERR_NEW_PROXY_TYPE: 4,
  TOX_ERR_NEW_PROXY_BAD_HOST: 5,
  TOX_ERR_NEW_PROXY_BAD_PORT: 6,
  TOX_ERR_NEW_PROXY_NOT_FOUND: 7,
  TOX_ERR_NEW_LOAD_ENCRYPTED: 8,
  TOX_ERR_NEW_LOAD_DECRYPTION_FAILED: 9,
  TOX_ERR_NEW_LOAD_BAD_FORMAT: 10,

  TOX_ERR_OPTIONS_NEW_OK: 0,
  TOX_ERR_OPTIONS_NEW_MALLOC: 1,

  TOX_ERR_BOOTSTRAP_OK: 0,
  TOX_ERR_BOOTSTRAP_NULL: 1,
  TOX_ERR_BOOTSTRAP_BAD_HOST: 2,
  TOX_ERR_BOOTSTRAP_BAD_PORT: 3,

  TOX_ERR_FRIEND_BY_PUBLIC_KEY_OK: 0,
  TOX_ERR_FRIEND_BY_PUBLIC_KEY_NULL: 1,
  TOX_ERR_FRIEND_BY_PUBLIC_KEY_NOT_FOUND: 2,

  TOX_ERR_FRIEND_GET_PUBLIC_KEY_OK: 0,
  TOX_ERR_FRIEND_GET_PUBLIC_KEY_FRIEND_NOT_FOUND: 1,

  TOX_ERR_GET_PORT_OK: 0,
  TOX_ERR_GET_PORT_NOT_BOUND: 1,

  TOX_ERR_SET_INFO_OK: 0,
  TOX_ERR_SET_INFO_NULL: 1,
  TOX_ERR_SET_INFO_TOO_LONG: 2,

  TOX_ERR_SET_TYPING_OK: 0,
  TOX_ERR_SET_TYPING_FRIEND_NOT_FOUND: 1,

  TOX_FILE_KIND_DATA: 0,
  TOX_FILE_KIND_AVATAR: 1,

  TOX_FILE_CONTROL_RESUME: 0,
  TOX_FILE_CONTROL_PAUSE: 1,
  TOX_FILE_CONTROL_CANCEL: 2,

  TOX_PROXY_TYPE_NONE: 0,
  TOX_PROXY_TYPE_HTTP: 1,
  TOX_PROXY_TYPE_SOCKS5: 2,

  TOX_SAVEDATA_TYPE_NONE: 0,
  TOX_SAVEDATA_TYPE_TOX_SAVE: 1,
  TOX_SAVEDATA_TYPE_SECRET_KEY: 2,

  TOX_PASS_KEY_LENGTH: 32,
  TOX_PASS_SALT_LENGTH: 32,
  TOX_PASS_ENCRYPTION_EXTRA_LENGTH: 80,

  TOX_ERR_DECRYPTION_OK: 0,
  TOX_ERR_DECRYPTION_NULL: 1,
  TOX_ERR_DECRYPTION_INVALID_LENGTH: 2,
  TOX_ERR_DECRYPTION_BAD_FORMAT: 3,
  TOX_ERR_DECRYPTION_KEY_DERIVATION_FAILED: 4,
  TOX_ERR_DECRYPTION_FAILED: 5,

  TOX_ERR_ENCRYPTION_OK: 0,
  TOX_ERR_ENCRYPTION_NULL: 1,
  TOX_ERR_ENCRYPTION_KEY_DERIVATION_FAILED: 2,
  TOX_ERR_ENCRYPTION_FAILED: 3,

  TOX_ERR_KEY_DERIVATION_OK: 0,
  TOX_ERR_KEY_DERIVATION_NULL: 1,
  TOX_ERR_KEY_DERIVATION_FAILED: 2,

  TOXDNS_MAX_RECOMMENDED_NAME_LENGTH: 32
};

module.exports = consts;
