/**
 * @file consts.js
 * Specifies constants and enum values defined in tox.h. All enum values
 * are assumed to start at 0 and increment once per possible value. This
 * could be an issue if updated versions of toxcore have new enum values
 * inserted, instead of appended.
 */

var consts = {
  TOX_KEY_SIZE: 32,
  TOX_FRIEND_ADDRESS_SIZE: (32 + 6),

  TOX_PUBLIC_KEY_SIZE: 32,
  TOX_SECRET_KEY_SIZE: 32,
  TOX_ADDRESS_SIZE: (32 + 6),
  TOX_MAX_NAME_LENGTH: 128,
  TOX_MAX_STATUS_MESSAGE_LENGTH: 1007,
  TOX_MAX_FRIEND_REQUEST_LENGTH: 1016,
  TOX_MAX_MESSAGE_LENGTH: 1372,
  TOX_MAX_CUSTOM_PACKET_SIZE: 1373,
  TOX_HASH_LENGTH: 32,
  TOX_FILE_ID_LENGTH: 32,
  TOX_MAX_FILENAME_LENGTH: 255,

  TOX_CONNECTION_NONE: 0,
  TOX_CONNECTION_TCP: 1,
  TOX_CONNECTION_UDP: 2,

  TOX_MESSAGE_TYPE_NORMAL: 0,
  TOX_MESSAGE_TYPE_ACTION: 1,

  TOX_ERR_FRIEND_ADD_OK: 0,
  TOX_ERR_FRIEND_ADD_NULL: 1,
  TOX_ERR_FRIEND_ADD_TOO_LONG: 2,
  TOX_ERR_FRIEND_ADD_NO_MESSAGE: 3,
  TOX_ERR_FRIEND_ADD_OWN_KEY: 4,
  TOX_ERR_FRIEND_ADD_ALREADY_SENT: 5,
  TOX_ERR_FRIEND_ADD_BAD_CHECKSUM: 6,
  TOX_ERR_FRIEND_ADD_SET_NEW_NOSPAM: 7,
  TOX_ERR_FRIEND_ADD_MALLOC: 8,

  TOX_ERR_FRIEND_CUSTOM_PACKET_OK: 0,
  TOX_ERR_FRIEND_CUSTOM_PACKET_NULL: 1,
  TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_FOUND: 2,
  TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_CONNECTED: 3,
  TOX_ERR_FRIEND_CUSTOM_PACKET_INVALID: 4,
  TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY: 5,
  TOX_ERR_FRIEND_CUSTOM_PACKET_TOO_LONG: 6,
  TOX_ERR_FRIEND_CUSTOM_PACKET_SENDQ: 7,

  TOX_ERR_FRIEND_QUERY_OK: 0,
  TOX_ERR_FRIEND_QUERY_NULL: 1,
  TOX_ERR_FRIEND_QUERY_FRIEND_NOT_FOUND: 2,

  TOX_ERR_FRIEND_SEND_MESSAGE_OK: 0,
  TOX_ERR_FRIEND_SEND_MESSAGE_NULL: 1,
  TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_FOUND: 2,
  TOX_ERR_FRIEND_SEND_MESSAGE_FRIEND_NOT_CONNECTED: 3,
  TOX_ERR_FRIEND_SEND_MESSAGE_SENDQ: 4,
  TOX_ERR_FRIEND_SEND_MESSAGE_TOO_LONG: 5,
  TOX_ERR_FRIEND_SEND_MESSAGE_EMPTY: 6,

  TOX_ERR_NEW_OK: 0,
  TOX_ERR_NEW_NULL: 1,
  TOX_ERR_NEW_MALLOC: 2,
  TOX_ERR_NEW_PORT_ALLOC: 3,
  TOX_ERR_NEW_PROXY_TYPE: 4,
  TOX_ERR_NEW_PROXY_BAD_HOST: 5,
  TOX_ERR_NEW_PROXY_BAD_PORT: 6,
  TOX_ERR_NEW_PROXY_NOT_FOUND: 7,
  TOX_ERR_NEW_LOAD_ENCRYPTED: 8,
  TOX_ERR_NEW_LOAD_DECRYPTION_FAILED: 9,
  TOX_ERR_NEW_LOAD_BAD_FORMAT: 10,

  TOX_ERR_OPTIONS_NEW_OK: 0,
  TOX_ERR_OPTIONS_NEW_MALLOC: 1,

  TOX_ERR_BOOTSTRAP_OK: 0,
  TOX_ERR_BOOTSTRAP_NULL: 1,
  TOX_ERR_BOOTSTRAP_BAD_HOST: 2,
  TOX_ERR_BOOTSTRAP_BAD_PORT: 3,

  TOX_ERR_GET_PORT_OK: 0,
  TOX_ERR_GET_PORT_NOT_BOUND: 1,

  TOX_ERR_SET_INFO_OK: 0,
  TOX_ERR_SET_INFO_NULL: 1,
  TOX_ERR_SET_INFO_TOO_LONG: 2,

  TOX_ERR_SET_TYPING_OK: 0,
  TOX_ERR_SET_TYPING_FRIEND_NOT_FOUND: 1,

  TOX_PROXY_TYPE_NONE: 0,
  TOX_PROXY_TYPE_HTTP: 1,
  TOX_PROXY_TYPE_SOCKS5: 2
};

module.exports = consts;
