/**
 * @file consts.js
 * Specifies constants and enum values defined in tox.h. All enum values
 * are assumed to start at 0 and increment once per possible value. This
 * could be an issue if updated versions of toxcore have new enum values
 * inserted, instead of appended.
 */

var consts = {
  TOX_ERR_FRIEND_CUSTOM_PACKET_OK: 0,
  TOX_ERR_FRIEND_CUSTOM_PACKET_NULL: 1,
  TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_FOUND: 2,
  TOX_ERR_FRIEND_CUSTOM_PACKET_FRIEND_NOT_CONNECTED: 3,
  TOX_ERR_FRIEND_CUSTOM_PACKET_INVALID: 4,
  TOX_ERR_FRIEND_CUSTOM_PACKET_EMPTY: 5,
  TOX_ERR_FRIEND_CUSTOM_PACKET_TOO_LONG: 6,
  TOX_ERR_FRIEND_CUSTOM_PACKET_SENDQ: 7,

  TOX_ERR_NEW_OK: 0,
  TOX_ERR_NEW_NULL: 1,
  TOX_ERR_NEW_MALLOC: 2,
  TOX_ERR_NEW_PORT_ALLOC: 3,
  TOX_ERR_NEW_PROXY_TYPE: 4,
  TOX_ERR_NEW_PROXY_BAD_HOST: 5,
  TOX_ERR_NEW_PROXY_BAD_PORT: 6,
  TOX_ERR_NEW_PROXY_NOT_FOUND: 7,
  TOX_ERR_NEW_LOAD_ENCRYPTED: 8,
  TOX_ERR_NEW_LOAD_DECRYPTION_FAILED: 9,
  TOX_ERR_NEW_LOAD_BAD_FORMAT: 10,

  TOX_ERR_OPTIONS_NEW_OK: 0,
  TOX_ERR_OPTIONS_NEW_MALLOC: 1,

  TOX_ERR_BOOTSTRAP_OK: 0,
  TOX_ERR_BOOTSTRAP_NULL: 1,
  TOX_ERR_BOOTSTRAP_BAD_HOST: 2,
  TOX_ERR_BOOTSTRAP_BAD_PORT: 3,

  TOX_ERR_GET_PORT_OK: 0,
  TOX_ERR_GET_PORT_NOT_BOUND: 1,

  TOX_PROXY_TYPE_NONE: 0,
  TOX_PROXY_TYPE_HTTP: 1,
  TOX_PROXY_TYPE_SOCKS5: 2
};

module.exports = consts;
